implement all endpoints
dglazkoff/go-musthave-diploma-tpl pull request #1
Opened 2024-08-22 14:17 UTC by dglazkoff

2024-08-26 14:12 UTC, tmvrus requested changes
- тест платформы должны проходить
- хотя бы из приличия напиши пару своих тестов
- решение получилось крайне ненадежное

2024-08-26 14:12 UTC, tmvrus commented on internal/api/order.go
> +		writer.WriteHeader(http.StatusBadRequest)
return?

2024-08-26 14:12 UTC, tmvrus commented on internal/server.go
> +	}
тут панику бросать неуместно, поскольку можно вернуть ошибку
https://go.dev/wiki/CodeReviewComments#dont-panic

2024-08-26 14:12 UTC, tmvrus commented on internal/service/accrual.go
> +		fmt.Println(response.StatusCode())
fmt для логирования не предназначен

2024-08-26 14:12 UTC, tmvrus commented on internal/service/accrual.go
> +		}
а это зачем?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/accrual.go
> +				return
- что будет если после UpdateOrder сервис перезапустят для обновления и UpdateBalance вы выпонится?
- что будет если UpdateOrder вернет ошибку, баланс все равно нужно обновить?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/accrual.go
> +	for {
а что если в процессе этого цикла сервис нужно будет перезапустить для хотфикса? как заказы получат свои бонусы?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/service.go
> +//}
закоменченного кода в рабочем проекте быть не должно

2024-08-26 14:12 UTC, tmvrus commented on internal/service/user.go
> +	_, err = s.storage.UpdateUser(ctx, copyUser)
что произойдет если между GetUserByLogin и UpdateUser придет другой запрос и загонит баланс в 0?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/user.go
> +	copyUser := user
зачем это?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/withdrawal.go
> +	_, err = s.storage.AddWithdrawal(ctx, models.Withdrawals{ID: orderNumber, UserId: userId, Sum: sum, ProcessedAt: time.Now().Format(time.RFC3339)})
что будет если между UpdateBalance и AddWithdrawal другой запрос спишет баланс до 0?

2024-08-26 14:12 UTC, tmvrus commented on internal/service/user.go
> +	// может ли за время работы функции другой поток создать юзера с таким же логином?
если за время работы другой поток создаст пользователя, то вся логика развалится, по этому ее надо переписать

2024-08-30 11:44 UTC, dglazkoff commented on internal/service/accrual.go
> +		}
Обрабатываю случай:
204 - заказ не зарегистрирован в системе расчета.

через секунду попытаюсь еще раз сделать запрос, возможно к этому времени уже дойдет заказ до системы расчета

2024-08-30 12:26 UTC, dglazkoff commented on internal/service/user.go
> +	copyUser := user
чтобы не мутировать данные, которые приходят из другой функции. если бы мы тестировали UpdateBalance и поменяли бы баланс у структуры, которая приходит в s.storage.GetUserByLogin(ctx, userId), при этом эта же структура использовалась бы в других тестах, то в другие тесты приходила бы структура с измененным балансом

2024-08-30 15:50 UTC, tmvrus commented on internal/service/user.go
> +	copyUser := user
Ну то есть ты сделал это что бы писать тесты?

2024-08-30 15:52 UTC, dglazkoff commented on internal/service/user.go
> +	copyUser := user
ну просто как правило хорошего тона, это же как пример тесты привел. привык писать чистые функции

2024-08-30 16:10 UTC, tmvrus commented on internal/service/user.go
> +	copyUser := user
судя по сигнатуре
```
GetUserByLogin(ctx context.Context, login string) (user models.User, err error)
```
ф-я возвращает значение а не ссылку, мутировать его не получится и так

2024-08-31 09:01 UTC, dglazkoff commented on internal/service/user.go
> +	copyUser := user
да, спасибо, перепутал логику передачи аргументов с JS

2024-09-02 16:17 UTC, dglazkoff commented on internal/service/user.go
> +	_, err = s.storage.UpdateUser(ctx, copyUser)
поставил блокировку на чтение в транзакции

2024-09-03 09:08 UTC, dglazkoff commented on internal/service/withdrawal.go
> +	_, err = s.storage.AddWithdrawal(ctx, models.Withdrawals{ID: orderNumber, UserId: userId, Sum: sum, ProcessedAt: time.Now().Format(time.RFC3339)})
кажется что проблему решает добавление блокировки таблицы при UpdateBalance. тогда транзакция упадет с ошибкой при вычислении нового баланса

2024-09-03 09:17 UTC, dglazkoff commented on internal/service/user.go
> +	// может ли за время работы функции другой поток создать юзера с таким же логином?
добавил транзакцию и блокировку таблицы при регистрации пользователя

2024-09-03 09:41 UTC, dglazkoff commented on internal/service/accrual.go
> +				return
здесь вижу два решения:
1. добавить горутину которая на старт сервера пройдется по базе и все ордеры в необработанном статусе соберет и отправит в accrual сервис
2. использовать горутину из пункта выше но запускать ее не только на старт сервера, но и периодически запускать с каким-то интервалом. при этом при получении очередного запроса не идти в accrual сервис

второй нравится меньше, потому что мы совершаем тяжелую операцию по поиску ордеров и это может сильно занимать базу, тем более при большом количестве записей, хотя кажется если выставить интервал побольше, то это не должно быть большой проблемой. хотя второй способ помогает избежать проблем, когда по какой-то причине мы после получения ордера не сделали отправку в accrual сервис, можно сказать что получается декларативное решение.

2024-09-06 11:54 UTC, dglazkoff commented
У меня так и не получилось написать качественные тесты. Много на это времени потратил, но так и не смог написать тесты ни на ответ StatusTooManyRequests, потому что не понял как в go делать fake timers, ни на processing статус, потому что не понял как работать с несколькими созданиями транзакций. К сожалению нет времени дальше продолжать разбираться, потому что и так отдаю в последний момент работу

2024-09-08 18:16 UTC, tmvrus approved these changes

2024-09-22 08:39 UTC, merged